os: linux
language: c
compiler: gcc
env:
  global:
    - MAKEOPTS=-j3
    - GLOBAL_CFLAGS='-O2 -Wall'
    - GLOBAL_CONFIGURE_ARGS='--prefix=/usr'
matrix:
  fast_finish: true
  include:
    - compiler: ": MinGW64 ncurses"
      env: UBUNTU_DEPS='gcc-mingw-w64-x86-64' EXTRA_DEPS='pkg-config yasm' CROSS_BINPKGS='x86_64-w64-mingw32+ncurses' BUILD_CFLAGS='-Werror' CONFIGURE_ARGS='--enable-other-drivers --enable-keccak --enable-scrypt --without-system-libbase58 --host=x86_64-w64-mingw32 --disable-knc --disable-bfsb --disable-jingtian --disable-metabank --disable-minergate --disable-titan --disable-kncasic --disable-minion'
    - compiler: ": Std Keccak"
      env: myCC='clang' UBUNTU_DEPS='libhidapi-dev linux-libc-dev' EXTRA_DEPS='pkg-config libncursesw5-dev libudev-dev libusb-1.0-0-dev libevent-dev libmicrohttpd-dev libi2c-dev yasm libsensors4-dev' CONFIGURE_ARGS='--enable-keccak'
  exclude:
    - compiler: gcc
install:
  - bash .travis.deps
script:
  - bash .travis.script
